import Foundation

/// Writes cookies in Netscape cookie file format for yt-dlp.
enum NetscapeCookieWriter {
    static func writeCookies(for url: URL, from storage: HTTPCookieStorage = .shared) throws -> URL? {
        guard let cookies = storage.cookies(for: url), !cookies.isEmpty else {
            return nil
        }
        
        let tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("nexus-cookies", isDirectory: true)
        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
        
        let fileURL = tempDir.appendingPathComponent("cookies_\(UUID().uuidString).txt")
        var lines: [String] = [
            "# Netscape HTTP Cookie File",
            "# This file was generated by Nexus"
        ]
        
        for cookie in cookies {
            let domain = cookie.domain.isEmpty ? (url.host ?? "") : cookie.domain
            let flag = domain.hasPrefix(".") ? "TRUE" : "FALSE"
            let path = cookie.path.isEmpty ? "/" : cookie.path
            let secure = cookie.isSecure ? "TRUE" : "FALSE"
            let expires = Int(cookie.expiresDate?.timeIntervalSince1970 ?? 0)
            lines.append(
                "\(domain)\t\(flag)\t\(path)\t\(secure)\t\(expires)\t\(cookie.name)\t\(cookie.value)"
            )
        }
        
        try lines.joined(separator: "\n").write(to: fileURL, atomically: true, encoding: .utf8)
        return fileURL
    }
    
    static func cleanup(_ fileURL: URL?) {
        guard let fileURL else { return }
        try? FileManager.default.removeItem(at: fileURL)
    }
}
